; ==============================================================================
; KABIRA POS - PRODUCTION WINDOWS INSTALLER
; ==============================================================================

#define MyAppName "KaBiRa POS"
#define MyAppVersion "2.5.0"
#define MyAppPublisher "KaBiRa POS Systems Corp"
#define MyAppURL "https://kabirapos.com"
#define MyAppExeName "KaBiRaPosBridge.exe"

[Setup]
AppId={{7894A8F1-0B29-4E76-88B9-99412F589A02}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}

AllowNoIcons=yes

OutputDir=..\..\dist\installer
OutputBaseFilename=KabiraPOS-Setup

Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern

PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

CloseApplications=yes
RestartApplications=no

UninstallDisplayName={#MyAppName}
Uninstallable=yes

SetupLogging=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

; ==============================================================================
; TASKS
; ==============================================================================

[Tasks]

Name: "desktopicon"; \
Description: "{cm:CreateDesktopIcon}"; \
GroupDescription: "{cm:AdditionalIcons}"

; ==============================================================================
; FILES
; ==============================================================================

[Files]

; ------------------------------------------------------------------------------
; KaBiRa POS production backend
; ------------------------------------------------------------------------------

Source: "..\..\dist\server.cjs"; \
DestDir: "{app}\Client"; \
Flags: ignoreversion

; Source map is optional.
Source: "..\..\dist\server.cjs.map"; \
DestDir: "{app}\Client"; \
Flags: ignoreversion skipifsourcedoesntexist

; ------------------------------------------------------------------------------
; KaBiRa POS frontend entry point
; ------------------------------------------------------------------------------

Source: "..\..\dist\index.html"; \
DestDir: "{app}\Client"; \
Flags: ignoreversion

; ------------------------------------------------------------------------------
; Frontend production assets
; ------------------------------------------------------------------------------

Source: "..\..\dist\assets\*"; \
DestDir: "{app}\Client\assets"; \
Flags: ignoreversion recursesubdirs createallsubdirs

; ------------------------------------------------------------------------------
; Backend Node dependencies
; ------------------------------------------------------------------------------

Source: "..\..\dist\node_modules\*"; \
DestDir: "{app}\Client\node_modules"; \
Flags: ignoreversion recursesubdirs createallsubdirs

; ------------------------------------------------------------------------------
; Other root-level production files that may be generated by the web build
; ------------------------------------------------------------------------------

Source: "..\..\dist\*.png"; \
DestDir: "{app}\Client"; \
Flags: ignoreversion skipifsourcedoesntexist

Source: "..\..\dist\*.svg"; \
DestDir: "{app}\Client"; \
Flags: ignoreversion skipifsourcedoesntexist

Source: "..\..\dist\*.ico"; \
DestDir: "{app}\Client"; \
Flags: ignoreversion skipifsourcedoesntexist

Source: "..\..\dist\*.webmanifest"; \
DestDir: "{app}\Client"; \
Flags: ignoreversion skipifsourcedoesntexist

Source: "..\..\dist\sw.js"; \
DestDir: "{app}\Client"; \
Flags: ignoreversion skipifsourcedoesntexist

Source: "..\..\dist\registerSW.js"; \
DestDir: "{app}\Client"; \
Flags: ignoreversion skipifsourcedoesntexist

Source: "..\..\dist\workbox-*.js"; \
DestDir: "{app}\Client"; \
Flags: ignoreversion skipifsourcedoesntexist

; ------------------------------------------------------------------------------
; Private Node.js runtime
; ------------------------------------------------------------------------------

Source: "..\..\dist\runtime\node.exe"; \
DestDir: "{app}\Runtime"; \
Flags: ignoreversion

; ------------------------------------------------------------------------------
; Main KaBiRa POS launchers
; ------------------------------------------------------------------------------

Source: "..\Start-KaBiRaPOS.bat"; \
DestDir: "{app}"; \
Flags: ignoreversion

Source: "..\Launch-KaBiRaPOS.vbs"; \
DestDir: "{app}"; \
Flags: ignoreversion

; ------------------------------------------------------------------------------
; .NET 8 Hardware Bridge
; ------------------------------------------------------------------------------

Source: "..\..\dist\bridge\*"; \
DestDir: "{app}\Bridge"; \
Flags: ignoreversion recursesubdirs createallsubdirs

; ------------------------------------------------------------------------------
; Native KaBiRa Customer Display (embedded WebView2, no Edge browser chrome)
; ------------------------------------------------------------------------------

Source: "..\..\dist\customer-display\*"; \
DestDir: "{app}\CustomerDisplay"; \
Flags: ignoreversion recursesubdirs createallsubdirs

; ------------------------------------------------------------------------------
; Hardware Bridge service installation script
; ------------------------------------------------------------------------------

Source: "..\install-service.ps1"; \
DestDir: "{app}\Bridge"; \
Flags: ignoreversion

; ==============================================================================
; SHORTCUTS
; ==============================================================================

[Icons]

Name: "{group}\{#MyAppName}"; \
Filename: "{sys}\wscript.exe"; \
Parameters: """{app}\Launch-KaBiRaPOS.vbs"""; \
WorkingDir: "{app}"; \
IconFilename: "{app}\Client\favicon.ico"

Name: "{autodesktop}\{#MyAppName}"; \
Filename: "{sys}\wscript.exe"; \
Parameters: """{app}\Launch-KaBiRaPOS.vbs"""; \
WorkingDir: "{app}"; \
IconFilename: "{app}\Client\favicon.ico"; \
Tasks: desktopicon

Name: "{group}\Uninstall {#MyAppName}"; \
Filename: "{uninstallexe}"

; ==============================================================================
; INSTALL ACTIONS
; ==============================================================================

[Run]

; Install and start Hardware Bridge Windows service.
Filename: "powershell.exe"; \
Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\Bridge\install-service.ps1"" -InstallPath ""{app}\Bridge"""; \
StatusMsg: "Installing KaBiRa POS Hardware Bridge..."; \
Flags: runhidden waituntilterminated

; Launch KaBiRa POS after installation without showing a console window.
Filename: "{sys}\wscript.exe"; \
Parameters: """{app}\Launch-KaBiRaPOS.vbs"""; \
Description: "Launch KaBiRa POS"; \
WorkingDir: "{app}"; \
Flags: postinstall nowait skipifsilent

; ==============================================================================
; UNINSTALL
; ==============================================================================

[UninstallRun]

; Stop and remove Hardware Bridge service.
Filename: "powershell.exe"; \
Parameters: "-NoProfile -ExecutionPolicy Bypass -Command ""Stop-Service -Name 'KaBiRaPOSBridge' -Force -ErrorAction SilentlyContinue; sc.exe delete KaBiRaPOSBridge | Out-Null"""; \
Flags: runhidden waituntilterminated

; Stop native KaBiRa customer display.
Filename: "powershell.exe"; \
Parameters: "-NoProfile -ExecutionPolicy Bypass -Command ""Get-Process -Name 'KaBiRaCustomerDisplay' -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue"""; \
Flags: runhidden waituntilterminated

; Stop only the KaBiRa POS Node backend.
; Do NOT terminate unrelated Node processes.
Filename: "powershell.exe"; \
Parameters: "-NoProfile -ExecutionPolicy Bypass -Command ""Get-CimInstance Win32_Process -Filter 'Name=''node.exe''' -ErrorAction SilentlyContinue | Where-Object {{ $_.CommandLine -like '*KaBiRa POS*server.cjs*' }} | ForEach-Object {{ Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }}"""; \
Flags: runhidden waituntilterminated

; ==============================================================================
; INSTALL / UPGRADE PROCESS MANAGEMENT
; ==============================================================================

[Code]

procedure StopKaBiRaProcesses();
var
  ResultCode: Integer;
begin

  { Stop existing Hardware Bridge service before replacing files. }

  Exec(
    'powershell.exe',
    '-NoProfile -ExecutionPolicy Bypass -Command "Stop-Service -Name ''KaBiRaPOSBridge'' -Force -ErrorAction SilentlyContinue"',
    '',
    SW_HIDE,
    ewWaitUntilTerminated,
    ResultCode
  );

  { Stop native customer display before replacing its executable. }

  Exec(
    'powershell.exe',
    '-NoProfile -ExecutionPolicy Bypass -Command "Get-Process -Name ''KaBiRaCustomerDisplay'' -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue"',
    '',
    SW_HIDE,
    ewWaitUntilTerminated,
    ResultCode
  );

  { Stop only KaBiRa POS Node backend processes. }

  Exec(
    'powershell.exe',
    '-NoProfile -ExecutionPolicy Bypass -Command "Get-CimInstance Win32_Process -Filter ''Name=''''node.exe'''''' -ErrorAction SilentlyContinue | Where-Object {{ $_.CommandLine -like ''*KaBiRa POS*server.cjs*'' }} | ForEach-Object {{ Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }}"',
    '',
    SW_HIDE,
    ewWaitUntilTerminated,
    ResultCode
  );

  Sleep(1000);

end;


function PrepareToInstall(var NeedsRestart: Boolean): String;
begin

  StopKaBiRaProcesses();

  NeedsRestart := False;

  Result := '';

end;
